name: Continuous Delivery

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Bot Environment (prd, tst, custom, straykids, nayeon)'
        required: false
  push:
    branches: [testing, production]

permissions:
  contents: read
  packages: write

env:
  # Uses docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  REPOSITORY_NAME: ${{ github.event.repository.name }}

jobs:
  Publish:
    name: Publish image to GHCR 🚀
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref_name }}

      - name: Extract version from package.json
        id: package_version
        uses: saionaro/extract-package-version@v1.2.1

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@6a58db7e0d21ca03e6c44877909e80e45217eed2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker images
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=${{ steps.package_version.outputs.version }}
            type=raw,value=${{ steps.package_version.outputs.version }}.${{ github.run_number }}
            type=raw,value=latest,enable=${{ endsWith(github.ref, 'production') }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4.1.0
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy_production:
    name: Birthdayy 🎂
    needs: Publish
    if: |
      github.event.inputs.environment == 'prd' || (github.event.inputs.environment == null && github.ref == 'refs/heads/production')
    uses: ./.github/workflows/deploy.yml
    secrets:
      DOCKER_TAG: 'production'
      DOCKER_NETWORK: '${{ secrets.DOCKER_NETWORK }}'
      DOPPLER_TOKEN: '${{ secrets.DOPPLER_TOKEN_PRODUCTION }}'
      SSH_HOST: '${{ secrets.SSH_HOST }}'
      SSH_KEY: '${{ secrets.SSH_PRIVATE_KEY }}'
      SSH_USER: '${{ secrets.SSH_USER }}'

  deploy_custom:
    name: Custom 🎂
    needs: Publish
    if: |
      github.event.inputs.environment == 'custom' || (github.event.inputs.environment == null && github.ref == 'refs/heads/production')
    uses: ./.github/workflows/deploy.yml
    secrets:
      DOCKER_TAG: 'custom'
      DOCKER_NETWORK: '${{ secrets.DOCKER_NETWORK }}'
      DOPPLER_TOKEN: '${{ secrets.DOPPLER_TOKEN_BIRTHDAYY_CUSTOM }}'
      SSH_HOST: '${{ secrets.SSH_HOST }}'
      SSH_KEY: '${{ secrets.SSH_PRIVATE_KEY }}'
      SSH_USER: '${{ secrets.SSH_USER }}'

  deploy_staykids:
    name: StrayKids 🎂
    needs: Publish
    if: |
      github.event.inputs.environment == 'straykids' || (github.event.inputs.environment == null && github.ref == 'refs/heads/production')
    uses: ./.github/workflows/deploy.yml
    secrets:
      DOCKER_TAG: 'straykids'
      DOCKER_NETWORK: '${{ secrets.DOCKER_NETWORK }}'
      DOPPLER_TOKEN: '${{ secrets.DOPPLER_TOKEN_STRAYKIDS }}'
      SSH_HOST: '${{ secrets.SSH_HOST }}'
      SSH_KEY: '${{ secrets.SSH_PRIVATE_KEY }}'
      SSH_USER: '${{ secrets.SSH_USER }}'

  deploy_nayeon:
    name: NAYEON 🎂
    needs: Publish
    if: |
      github.event.inputs.environment == 'nayeon' || (github.event.inputs.environment == null && github.ref == 'refs/heads/production')
    uses: ./.github/workflows/deploy.yml
    secrets:
      DOCKER_TAG: 'nayeon'
      DOCKER_NETWORK: '${{ secrets.DOCKER_NETWORK }}'
      DOPPLER_TOKEN: '${{ secrets.DOPPLER_TOKEN_NAYEON }}'
      SSH_HOST: '${{ secrets.SSH_HOST }}'
      SSH_KEY: '${{ secrets.SSH_PRIVATE_KEY }}'
      SSH_USER: '${{ secrets.SSH_USER }}'

  deploy_testing:
    name: Testing 🧪
    needs: Publish
    if: |
      github.event.inputs.environment == 'tst' || (github.event.inputs.environment == null && github.ref == 'refs/heads/testing')
    uses: ./.github/workflows/deploy.yml
    secrets:
      DOCKER_TAG: 'testing'
      IMAGE_TAG: 'testing'
      DOCKER_NETWORK: '${{ secrets.DOCKER_NETWORK }}'
      DOPPLER_TOKEN: '${{ secrets.DOPPLER_TOKEN_TESTING }}'
      SSH_HOST: '${{ secrets.SSH_HOST }}'
      SSH_KEY: '${{ secrets.SSH_PRIVATE_KEY }}'
      SSH_USER: '${{ secrets.SSH_USER }}'
