name: Deploy using Docker via SSH

on:
  workflow_call:
    secrets:
      SSH_HOST:
        required: true
      SSH_USER:
        required: true
      SSH_KEY:
        required: true
      DOCKER_TAG:
        required: true
      DOPPLER_TOKEN:
        required: true
      DOCKER_NETWORK:
        required: true
      IMAGE_TAG:
        required: false
      GHCR_USER:
        required: false
      GHCR_TOKEN:
        required: false

env:
  CONTAINER_NAME: ${{ github.event.repository.name }}-${{ secrets.DOCKER_TAG }}
  REPOSITORY_NAME: ghcr.io/$( echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]' ):${{ secrets.IMAGE_TAG || 'latest' }}

jobs:
  ssh:
    name: SSH and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Login to GHCR.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER || github.actor }}
          password: ${{ secrets.GHCR_TOKEN || github.token }}

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: 'placeholder'
          config: |
            Host ${{ secrets.SSH_HOST }}
            HostName ${{ secrets.SSH_HOST }}
            User ${{ secrets.SSH_USER }}
            StrictHostKeyChecking no
      - name: Add known hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Run commands in remote host
        run: |
          ssh -T ${{ secrets.SSH_HOST }} "docker stop ${{ env.CONTAINER_NAME }} || true \\
          && docker rm ${{ env.CONTAINER_NAME }} || true \\
          && docker image prune -a -f \\
          && docker run -d --restart=unless-stopped --net ${{ secrets.DOCKER_NETWORK }} --env DOPPLER_TOKEN=${{ secrets.DOPPLER_TOKEN }} --name ${{ env.CONTAINER_NAME }} ${{ env.REPOSITORY_NAME }}"
